In [72]:
#Correlation Matrix

import numpy as np
import pandas as pd

data = pd.read_csv('Gender.csv')
data.head()

correlation_matrix = np.corrcoef(data.T)
print(correlation_matrix)

[[ 1.         -1.         -0.19780665 -0.16947705 -0.23142859 -0.16803345
  -0.14323617 -0.10417506 -0.12949516 -0.24431894 -0.23235401 -0.24191047
  -0.11444974 -0.24227123 -0.21195104 -0.2021281  -0.24292633 -0.24541294
  -0.27120761 -0.20460147 -0.20371076 -0.2806666  -0.19495254 -0.22733311
  -0.21258009 -0.23217845 -0.20654831 -0.23570226]
 [-1.          1.          0.19780665  0.16947705  0.23142859  0.16803345
   0.14323617  0.10417506  0.12949516  0.24431894  0.23235401  0.24191047
   0.11444974  0.24227123  0.21195104  0.2021281   0.24292633  0.24541294
   0.27120761  0.20460147  0.20371076  0.2806666   0.19495254  0.22733311
   0.21258009  0.23217845  0.20654831  0.23570226]
 [-0.19780665  0.19780665  1.          0.92958669  0.85740571  0.70098129
   0.88144426  0.87727748  0.91497328  0.97287279  0.97031466  0.96627241
   0.84378206  0.90830538  0.98641038  0.96820258  0.90373605  0.94317842
   0.92244468  0.75394713  0.98824863  0.9627886   0.77298327  0.7967042
   0.971451

In [46]:
#T-Test code taken from 
#https://machinelearningmastery.com/how-to-code-the-students-t-test-from-scratch-in-python/

import csv
from math import sqrt
from numpy import mean
from scipy.stats import sem
from scipy.stats import t

# function for calculating the t-test for two independent samples
def independent_ttest(data1, data2, alpha):
    # calculate means
    mean1, mean2 = mean(data1), mean(data2)
    
    # calculate standard errors
    se1, se2 = sem(data1), sem(data2)
    
    # standard error on the difference between the samples
    sed = sqrt(se1**2.0 + se2**2.0)
    
    # calculate the t statistic
    t_stat = (mean1 - mean2) / sed
    
    # degrees of freedom
    df = len(data1) + len(data2) - 2
    
    # calculate the critical value
    cv = t.ppf(1.0 - alpha, df)
    
    # calculate the p-value
    p = (1.0 - t.cdf(abs(t_stat), df)) * 2.0
    
    # return everything
    return t_stat, df, cv, p


#Put csv results into a 2d array and a phylum array
results = []
phylum = []

with open("Gender.csv") as csvfile:
    reader = csv.reader(csvfile) 
    phylum = next(reader)
    for row in reader:
        results.append(row)

phylum.remove("Male")
phylum.remove("Female")

final = [list( map(int,i) ) for i in results] 
# print(results)
# print(phylum)
# print(final)

index = 2
sig_phylum = []
bacteria_list = []
for phy in phylum:    
    print(phy)
    test_passed = 0
    
    #separate each phylum data by gender
    male = []
    female = []

    for row in final:
        if row[0] is 1: #male
            male.append(row[index])
        else: #female
            female.append(row[index])

    # calculate the t test
    alpha = 0.05
    t_stat, df, cv, p = independent_ttest(male, female, alpha)
    print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
    
    # interpret via critical value
#     if abs(t_stat) <= cv:
#         print('Accept null hypothesis that the means are equal.')
#     else:
#         print('Reject the null hypothesis that the means are equal.')
    if abs(t_stat) > cv:
        test_passed += 1
        
    # interpret via p-value
#     if p > alpha:
#         print('Accept null hypothesis that the means are equal.')
#     else:
#         print('Reject the null hypothesis that the means are equal.')
    if p <= alpha:
        test_passed += 1
        
    print("tests passed: ", test_passed)
    
    if(test_passed is 2):
        sig_phylum.append(phy)
        bacteria_list.append(index - 2)
        
    index += 1;

print("\nphylums that are tested to be 95% confident of independent: \n", sig_phylum, 
      "\ncorresponding phylum indices: \n", bacteria_list)

pFirmicutes
t=-1.801, df=26, cv=1.706, p=0.083
tests passed:  1
pProteobacteria
t=-1.536, df=26, cv=1.706, p=0.137
tests passed:  0
pBacteroidetes
t=-2.125, df=26, cv=1.706, p=0.043
tests passed:  2
pActinobacteria
t=-1.520, df=26, cv=1.706, p=0.140
tests passed:  0
pFusobacteria
t=-0.992, df=26, cv=1.706, p=0.330
tests passed:  0
pSpirochaetes
t=-0.904, df=26, cv=1.706, p=0.374
tests passed:  0
pCyanobacteria
t=-1.156, df=26, cv=1.706, p=0.258
tests passed:  0
pThermotogae
t=-2.244, df=26, cv=1.706, p=0.034
tests passed:  2
pTenericutes
t=-2.129, df=26, cv=1.706, p=0.043
tests passed:  2
pChlamydiae
t=-2.215, df=26, cv=1.706, p=0.036
tests passed:  2
pSynergistetes
t=-1.030, df=26, cv=1.706, p=0.312
tests passed:  0
pThermi
t=-2.208, df=26, cv=1.706, p=0.036
tests passed:  2
pChloroflexi
t=-1.924, df=26, cv=1.706, p=0.065
tests passed:  1
pCrenarchaeota
t=-1.838, df=26, cv=1.706, p=0.078
tests passed:  1
pThermodesulfobacteria
t=-2.223, df=26, cv=1.706, p=0.035
tests passed:  2
pVerru

In [74]:
#Correlation Matrix for Bacteroidetes

import numpy as np
import pandas as pd

data = pd.read_csv('GenderBacteroidetes.csv')
data.head()

correlation_matrix = np.corrcoef(data.T)
print(correlation_matrix)

[[ 1.         -1.         -0.23142859]
 [-1.          1.          0.23142859]
 [-0.23142859  0.23142859  1.        ]]


In [47]:
#trying to write something that can create custom correlation matrix 
#for a specific column without having to keep making csv files
import numpy as np
import pandas as pd

data = []
# bacteria_list = [2, 7, 8, 9] #index in phylum of which bacteria I want to look at
displacement = 2 #starts at 2 to account for male, female columns
indices = np.array(bacteria_list) + displacement

for index in range(0, len(bacteria_list)):
    print("\tMale\t", "Female\t", phylum[bacteria_list[index]])

    #create a 2d array that would replace the csv file
    for row in results:
        r = []
        r.append(row[0])
        r.append(row[1])
        r.append(row[indices[index]])
        data.append(list(map(int, r)))

    df = pd.DataFrame(data)
    correlation_matrix = np.corrcoef(df.T)
    print(correlation_matrix, "\n")

	Male	 Female	 pBacteroidetes
[[ 1.         -1.         -0.23142859]
 [-1.          1.          0.23142859]
 [-0.23142859  0.23142859  1.        ]] 

	Male	 Female	 pThermotogae
[[ 1.         -1.         -0.15637113]
 [-1.          1.          0.15637113]
 [-0.15637113  0.15637113  1.        ]] 

	Male	 Female	 pTenericutes
[[ 1.         -1.         -0.12602617]
 [-1.          1.          0.12602617]
 [-0.12602617  0.12602617  1.        ]] 

	Male	 Female	 pChlamydiae
[[ 1.         -1.         -0.10847769]
 [-1.          1.          0.10847769]
 [-0.10847769  0.10847769  1.        ]] 

	Male	 Female	 pThermi
[[ 1.         -1.         -0.09665927]
 [-1.          1.          0.09665927]
 [-0.09665927  0.09665927  1.        ]] 

	Male	 Female	 pThermodesulfobacteria
[[ 1.         -1.         -0.08800773]
 [-1.          1.          0.08800773]
 [-0.08800773  0.08800773  1.        ]] 

	Male	 Female	 pVerrucomicrobia
[[ 1.         -1.         -0.08132216]
 [-1.          1.          0.081322